# DataSource Config
spring:
  datasource:
    url: jdbc:mysql://152.136.120.171:3306/TEST?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: lxj19990716
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 8082
